# Generated by Django 4.2.4 on 2023-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='default_pic/def.png', null=True, upload_to='profile_pic/')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.TextField(max_length=20)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
